travis:
  secure:
    BINSTAR_TOKEN: MeVjxigDzEprEC6RplTLI0KjVhquKpvTjbV81lMy/2TwyldHcd3xSzGQKiDQ+jmlF904lEenfDet5f38g/8hqOyq9ZNHvu3A2Aj9MWyEJ44oCgH5oaHL1Mx16q1qzAb/ja5TuaNyeI0yT3XCyfWmKWNLT/nWSuQ4oy/pFMGqhsQ7uRD3Y2/MWwXnvmNZjOVywqCVb9Hqyo9vwwBELtIdnYYLQJre4SMiA7f4qleSrFN53W+nflS8AK7bj39Nxblg2cF3u2f8skXyN4fywgTcaV74KqMrrZRATbMxaZJKYmtr+ndmt6XeW1hWDeL8lt2S/ToKhQfOCQx/ItOEC0CsxhpwKPZK4/jFQqVer6cx6jx1t8byqYk4q0pa6/uGOB3ppBPJPi+b4AJMaGe4oiSQgpNhbe4FpieH5BJQBgtN2VUt4kZzDWb4+fQNdgfVn7nx1Ha81srmE8aDjbqZ78irT1isSEvSHwlyY6Ctot/hQOaJ5xE0VB/3UhRdf4ERGehRfwprYLt/Af0Cegd76PD+cLpVmuXoruq0M4wMLS+qBtor5aAmzeWj5CxiCNkJ9z5kHdKHBhXmBB+p9mXwl2XhvBFwdp9s8IgQSqpgah+JFGrkCZQqJ3MlIrmhQ8L38izFUdTThRunt4d9eplBesMJr4KK9iqiOdNhmTxPOXhuGE0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
